### ISSUE TITLE
网卡白名单

### ISSUE THREAD

**Issue by ychw** [p455555555/Thinkpad-P1-EFI#3]
我买了个P1 Gen2，结果碰到网卡白名单。你碰到过吗？现在的BIOS版本是多少？

**Comment by p455555555** [comment]
> 我买了个P1 Gen2，结果碰到网卡白名单。你碰到过吗？现在的BIOS版本是多少？

P1 Gen2 我不清楚，我bios版本是1.19，没有网卡白名单

**Comment by ychw** [comment]
哦，我的是1.27，有白名单。你知道Bios在哪里吗，我可以试着刷一下

**Comment by p455555555** [comment]
> 哦，我的是1.27，有白名单。你知道Bios在哪里吗，我可以试着刷一下

我的是1代的电脑，bios跟2代的不一样

**Comment by p455555555** [comment]
> 哦，我的是1.27，有白名单。你知道Bios在哪里吗，我可以试着刷一下

这个是2代bios下载地址 https://think.lenovo.com.cn/support/driver/driverdetail.aspx?DEditid=65840&docTypeID=DOC_TYPE_DRIVER&driverID=undefined&treeid=13908&args=%3Fyt%3Dpt%26categoryid%3D13908%26CODEName%3DThinkPad%2520P1%2520%25E9%259A%2590%25E5%25A3%25AB%25202019%26SearchType%3D0%26wherePage%3D2%26needmt%3DThinkPad%2520P1%2520%25E9%259A%2590%25E5%25A3%25AB%25202019%2520%2520target%3D

**Comment by ychw** [comment]
OK thanks
