### ISSUE TITLE
苹果BCM94360CS2+转接卡

### ISSUE THREAD

**Issue by talbole** [p455555555/Thinkpad-P1-EFI#7]
Wi-Fi/蓝牙：苹果BCM94360CS2+转接卡，这个需要另外加延长线吗？还是直接插上就ok， 请问可以拍个图片看看吗？谢谢。

**Comment by p455555555** [comment]
请参考这位老哥的issues：https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/issues/11
